### ISSUE TITLE
[comment] Pretty great

### ISSUE THREAD

**Issue by TFWol** [eeetem/GPT3-Discord-Bot#2]
Just stating I've been playing around with the implementation. Works fine.
I had increased the limits since it's just me. Super addicting to mess with.
You're right too; this is pretty silly.
![cat](https://user-images.githubusercontent.com/9045213/145859172-9d63cae1-d1c4-4ad1-98a6-fbc36a5c9e06.png)

**Comment by eeetem** [comment]
I find that increasing the limit of messages too high often gets it's stuck in loops of similar responses - since it's looking back and seeing a group of similar responses and keeps going with the vibe. With low limits it's inteligent enough to still gather context but change the vibe/mood of conversation a bit more dynamically. Also increasing the limit exponentially increases the token usage. (disregard that this message is 4 months late, i missed the original notification)

**Comment by TFWol** [comment]
No problem, wasn't sure how opening an 'Issue' as a comment and then closing it would work.
Thanks for the tip.
